platform :ios, "9.0"
use_frameworks!

target 'ManaGuide' do
    pod 'DATASource'
    pod 'DATAStack'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Storage'
    pod 'FontAwesome.swift'
    pod 'GoogleSignIn'
    pod 'InAppSettingsKit'
    pod 'Kanna', '~> 2.1.0'
    pod 'ManaKit'
    pod 'MBProgressHUD'
    pod 'MMDrawerController'
    pod 'MMDrawerController+Storyboard'
    pod 'Networking'
    pod 'RATreeView', '~> 2.1.2'
    pod 'ReachabilitySwift'
    pod 'SimulatorStatusMagic', :configurations => ['Debug']
    pod 'SSZipArchive'
    pod 'Sync'
    pod 'TwitterKit'
    pod 'TwitterCore'
end

target 'ManaGuideTests' do
    pod 'DATASource'
    pod 'DATAStack'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Storage'
    pod 'FontAwesome.swift'
    pod 'GoogleSignIn'
    pod 'InAppSettingsKit'
    pod 'Kanna', '~> 2.1.0'
    pod 'ManaKit'
    pod 'MBProgressHUD'
    pod 'MMDrawerController'
    pod 'MMDrawerController+Storyboard'
    pod 'Networking'
    pod 'RATreeView', '~> 2.1.2'
    pod 'ReachabilitySwift'
    pod 'SimulatorStatusMagic', :configurations => ['Debug']
    pod 'SSZipArchive'
    pod 'Sync'
    pod 'TwitterKit'
    pod 'TwitterCore'end

target 'ManaGuideUITests' do
    pod 'DATASource'
    pod 'DATAStack'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Storage'
    pod 'FontAwesome.swift'
    pod 'GoogleSignIn'
    pod 'InAppSettingsKit'
    pod 'Kanna', '~> 2.1.0'
    pod 'ManaKit'
    pod 'MBProgressHUD'
    pod 'MMDrawerController'
    pod 'MMDrawerController+Storyboard'
    pod 'Networking'
    pod 'RATreeView', '~> 2.1.2'
    pod 'ReachabilitySwift'
    pod 'SimulatorStatusMagic', :configurations => ['Debug']
    pod 'SSZipArchive'
    pod 'Sync'
    pod 'TwitterKit'
    pod 'TwitterCore'
end

