# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone XS Max", # 6.5"
   "iPhone X", # 5.8"
   "iPhone 6 Plus", # 5.5"
   "iPhone 6", # 4.7"
   "iPhone 5", # 4"
   "iPad Pro (12.9-inch)",
   "iPad Pro (11-inch)",
   "iPad Pro (10.5-inch)",
   "iPad Pro (9.7-inch)"
])

languages([
   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
 scheme "ManaGuideUITests"

# Where should the resulting screenshots be stored?
 #output_directory "./screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
 clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

# reinstall_app true
erase_simulator true
