# Uncomment the lines below you want to change by removing the # in the beginning

scheme("Tests iOS")

# A list of devices you want to take the screenshots from
 devices([
  "iPhone 11 Pro Max",          #6.5in
  "iPhone 11 Pro",              #5.8in
  "iPhone 8 Plus",              #5.5in
  "iPhone SE (3rd generation)", #4.7in
  "iPad Pro (12.9-inch) (5th generation)", #12.9in
  "iPad Pro (11-inch) (3rd generation)",   #11in
  "iPad Air (3rd generation)",             #10.5in
  "iPad (6th generation)"                  #9.7in  
 ])

 languages([
   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
 ])

# The name of the scheme which contains the UI Tests
scheme("Tests iOS")

# Where should the resulting screenshots be stored?
#output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
